FILES = BoundedBuffer.java Producer.java Consumer.java ProducerConsumer.java
all:
	javac -g $(FILES)
run:
	java ProducerConsumer
clean:
	rm -f *.class
package:
	zip -r AnnaMarie-Love-HW4.zip $(FILES) Makefile README.txt